---
title: "Monte Carlo Visulization"
output: html_notebook
---
```{r}
library(gganimate)
library(tidyverse)
library(gridExtra)
library(magick)
options(digit = 6)
set.seed(42)
```
```{r}
N_SIM <- 1000000
mcRaw <- tibble(R1 = rnorm(N_SIM, 1, 0.04/12),
                R2 = rnorm(N_SIM, 1, 0.04/12)) %>%
  mutate(G = R1 /(R1+R2))
```
Create frequency table

```{r}
mcHist <- mcRaw %>%
  mutate(index = row_number()) %>% 
  pivot_longer(cols = c("R1", "R2", "G"),
               names_to = "Variable", 
               values_to = "value") %>% 
  mutate(round = if_else(Variable == "G", 
                             plyr::round_any(value, 5e-4),
                             plyr::round_any(value, 1e-3)))


```

```{r}
count_by_round <-mcHist %>%
  select(Variable, round) %>%
  group_by(Variable, round) %>%
  summarise(n = n(), .groups = "drop") %>%
  ungroup()

gplot <- count_by_round %>%
  filter(Variable == "G") %>% 
  ggplot(aes(round, n)) +
  facet_grid(~Variable) +
  geom_bar(stat = "identity", color="black") + 
  geom_vline(xintercept = 0.49, color="blue") + 
  geom_vline(xintercept = 0.51, color="blue") +
  theme_bw() + 
  theme(strip.text = element_text(size = 16, hjust = 0.1),
        axis.text.y = element_blank(),
        axis.text.x = element_text(angle=90, vjust=.5, hjust=1))

rplot <- count_by_round %>%
  filter(Variable != "G") %>% 
  ggplot(aes(round, n)) +
  facet_grid(~Variable) +
  geom_bar(stat = "identity", color="black") + 
  geom_vline(xintercept = 0.98, color="blue") + 
  geom_vline(xintercept = 1.02, color="blue") +
  theme_bw() + 
  theme(strip.text = element_text(size = 16, hjust = 0.1),
        axis.text.y = element_blank(),
        axis.text.x = element_text(angle=90, vjust=.5, hjust=1))
```
Combine Plots
```{r}
# Combine plots
plot = grid.arrange(rplot, gplot, nrow = 2)
```
```{r}
# alternatively, use geom_bar to generate histogram from raw data
gg <- mcHist %>%
  filter(Variable == "G") %>%
  ggplot(aes(x=round)) + 
  geom_bar(color="black", stat = "count", alpha = .3, fill = "transparent") +
  labs(x = "", y = "Frequency") +
  theme_bw() +
  theme(panel.grid = element_blank(),
        strip.text = element_text(size = 16, hjust = 0.1),
        axis.text.y = element_blank()) +
  geom_vline(xintercept = 0.49, color="blue") + geom_vline(xintercept = 0.51, color="blue")

gg
```


```{r}
# constants for animation
FPS = 10
N_FRAME = 201
```


```{r}
count_by_index <- function(mcHist, nframes=120) {
  # Initialization of variables
  data <- tibble(idx = integer(),
                 n_sample = integer(),
                 Variable = character(),
                 round = numeric(),
                 n = integer())
  N_SIM = max(mcHist$index)
  step <- floor(N_SIM / (nframes-1))
  data <- data %>% 
    add_row(tibble(idx = 1,
                 n_sample = 0,
                 Variable = c("G","R1", "R2"),
                 round = NA,
                 n = 0))

  for (i in 1:nframes-1) {
    # Data manipulation and summarization steps
    row <- mcHist %>%
           select(index, Variable, round) %>%
           filter(index <= step * i) %>%
           group_by(Variable, round) %>%
           summarise(n = n(), .groups = 'drop') %>%
           mutate(idx = i + 1,
                  n_sample = floor(step * i))
    # Append the summary data to the main data frame
    data <- data %>%
            add_row(row)
  }
  return(data)
}
```
```{r}
hist_anim_data <- count_by_index(mcHist, N_FRAME) %>% 
  arrange(idx)
```


Create gif for G and R

```{r}
# dot plot for first 5 samples 
tgplot <- mcHist %>%
  filter(index <= 5 & Variable == "G") %>%
  ggplot(aes(group = index, x = round)) + # group by index is important
  facet_grid(~Variable) +
  geom_point(aes(y=0), size = 5, color="black") + 
  geom_text(aes(x=0.5, y=0.1, label = format(value, digits = 5)), 
                position = position_dodge(width=0.9), color="blue", size = 10) +
  labs(x = "", y = "Frequency") +
  xlim(0.49, 0.51) +
  theme_bw() +
  theme(panel.grid = element_blank(),
    strip.text = element_text(size = 16, hjust = 0.1),
    axis.text.y = element_blank()) 

trplot <- mcHist %>%
  filter(index <= 5 & Variable != "G") %>%
  ggplot(aes(group = index, x = round)) + # group by index is important
  facet_grid(~Variable) +
  geom_point(aes(y=0), size = 5, color="black") + 
  geom_text(aes(x=1, y=0.1, label = format(value, digits = 5)), 
                position = position_dodge(width=0.9), color="blue", size = 10) +
  labs(x = "", y = "Frequency") +
    xlim(0.98, 1.02) +
    theme_bw() +
    theme(
      panel.grid = element_blank(),
      strip.text = element_text(size = 16, hjust = 0.1),
      axis.text.y = element_blank()
    )

```
Create GIF
```{r}
# Create GIF
r_anim <- trplot + transition_states(index)
rgif <- animate(r_anim,
                width = 800, height = 400,
                nframes = 5, 
                fps = 2.5,
                #renderer = magick_renderer()
                #renderer = gifski_renderer("./anim/tr.gif")
                renderer = file_renderer("./frames", prefix = "tr")
                )

g_anim <- tgplot + transition_states(index)
ggif <- animate(g_anim,
                width = 800, height = 400,
                nframes = 5,
                fps = 2.5,
                # renderer = magick_renderer()
                renderer = file_renderer("./frames", prefix = "tg")
                )
```
Combine 2 gifs
```{r}
#a_mgif <- image_read(rgif)
#b_mgif <- image_read(ggif)
new_gif <- image_append(c(rgif[1], ggif[1]), stack = TRUE)
for(i in 2:5) {
  combined <- image_append(c(rgif[i], ggif[i]), stack = TRUE)
  new_gif <- c(new_gif, combined)
}
anim_save("./anim/5dots.gif", new_gif)
```

```{r}
gplot <-
  hist_anim_data %>%
  filter(Variable == "G") %>%
  ggplot(aes(group = idx, round, n)) + # group by index is important
  facet_grid(~Variable) +
  geom_bar(stat = "identity") +
  geom_vline(xintercept = 0.49, color="blue") +
  geom_vline(xintercept = 0.51, color="blue") +
  labs(x = "", y = "Frequency") +
  theme_bw() +
  theme(panel.grid = element_blank(),
        strip.text = element_text(size = 32, hjust = 0.1),
        axis.text.y = element_blank())

gbar_anim <- gplot + transition_states(idx,  transition_length = 1, state_length = 0)
gbar_gif <- animate(gbar_anim,
                    nframes = N_FRAME,
                    width = 800, height = 260,
                    fps = FPS,
                    renderer = magick_renderer())
anim_save("./anim/gbar.gif", gbar_gif)
### For R1 and R2
rplot <-
  hist_anim_data %>%
  filter(Variable != "G") %>%
  ggplot(aes(group = idx, round, n)) + # group by index is important
  facet_grid(~Variable) +
  geom_bar(stat = "identity") +
  geom_vline(xintercept = 0.98, color="blue") +
  geom_vline(xintercept = 1.02, color="blue") +
  labs(x = "", y = "Frequency") +
  theme_bw() +
  theme(panel.grid = element_blank(),
        strip.text = element_text(size = 32, hjust = 0.1),
        axis.text.y = element_blank())

rbar_anim <- rplot + transition_states(idx,  transition_length = 1, state_length = 0)
rbar_gif <- animate(rbar_anim,
                    nframes = N_FRAME,
                    width = 800, height = 260,
                    fps = FPS,
                    renderer = magick_renderer())

anim_save("./anim/rbar.gif", gbar_gif)


```
```{r}
counter_gif <- hist_anim_data %>% 
  arrange(idx) %>% 
  ggplot(aes(x = 1, y = 1, label = n_sample)) +
  geom_text(color = 'blue', size = 32) +
  theme_void() +
  theme(plot.background = element_rect(fill = "white"),
        text = element_text(size = 32, hjust = 0))

counter_anim <- counter_gif + transition_states(idx, transition_length = 1, state_length = 0) +
  ease_aes('linear') +
  labs(title = 'Samples Generated', size = 24)

# Create the animation object
counter_anim_obj <- animate(counter_anim,
                            width = 800, height = 120,
                            nframes = N_FRAME,
                            fps = FPS,
                            renderer = magick_renderer() ) 

# Save the animation to a file
anim_save("./anim/counter.gif", counter_anim_obj)
```



```{backup}
# Create a counter 
counter <- tibble(count = 1:N_SIM,
                  time = seq(0, DURATION, length.out = N_SIM ))

# ggplot for counter
counter_gif <- ggplot(counter, aes(x = 1, y = 1, label = count)) +
  geom_text(color = 'blue', size = 32) +
  theme_void() +
  theme(plot.background = element_rect(fill = "white"),
        text = element_text(size = 32, hjust = 0))

counter_anim <- counter_gif + transition_time(time) +
  ease_aes('linear') +
  labs(title = 'Samples Generated', size = 24)

counter_gif <- animate(counter_anim,
                       width = 800, height = 120,
                       nframes = N_FRAME,
                       fps = FPS,
                       renderer = gifski_renderer("./anim/counter.gif"))
```

Combine 3 gifs
```{r}
a_mgif <- image_read(rbar_gif)
b_mgif <- image_read(gbar_gif)
c_mgif <- image_read(counter_gif)

new_gif <- image_append(c(a_mgif[1], b_mgif[1],  c_mgif[1]), stack = TRUE)
for(i in 2:N_FRAME) {
  combined <- image_append(c(a_mgif[i], b_mgif[i], c_mgif[i]), stack = TRUE)
  new_gif <- c(new_gif, combined)
}
anim_save("./anim/bar.gif", new_gif)
```